### PR TITLE
Support for Refget v2.0

### PR DESCRIPTION
**Pull request by tcezard**
Add new tests to support refget v2.0
Keep support for v1 as well

### CODE REVIEW

**Comment by tcezard** [comment]
Test are still failing as they were before but they do pass in my local machine and in 3.6, 3.8 and 3.9.
Next PR should switch to Github action

**Comment by andrewyatz** [comment]
At first read this looks great to me. One question I have is that our compliance suite requires the pre-loading of sequences. Our choice is pretty universal but a server might want to not load these but still check for general compliance. I'm wondering how we could facilitate that? Would service-info need to be extended? Is there a reason to wait to see what DRS does and follow their lead?

**Review by andrewyatz — APPROVED** [review]
Just run this locally against the ref v2 API. Glad to see things are working bar the service-info. I didn't see any GA4GH tests running but assume this is a service info issue.

**Comment by Chen2x** [comment]
@tcezard I tried generating a report on the server "https://www.ebi.ac.uk/ena/cram/" and I have gotten 3 failed tests with these messages. Is this the expected result?
Screen Shot 2022-12-08 at 3 43 10 PM

**Comment by tcezard** [comment]
Thank @Chen2x . The results you found makes sense.
I'll merge this PR now.

**Pull request merged**
